## Display
SIZE = WIDTH, HEIGHT = 800, 600
BTN_SIZE_LARGE = 120, 50 
BTN_SIZE_SMALL = 60, 60

TITLE_Y = 80
BTN_START_Y = HEIGHT - 250
BTN_CONTROL_Y = HEIGHT - 170
BTN_QUIT_Y = HEIGHT - 90

## Game balance
BALL_BASE_SPEED = 300
BALL_MAX_SPEED = 450
BALL_ACCELERATION_PERIOD = 1
BALL_ACCELERATION_VALUE = 1
BALL_RADIUS = 10

BAR_BASE_SPEED = 350
BAR_BASE_LENGTH = 120
BAR_Y = HEIGHT - 25

POINT_DECREASE_PERIOD = 1
POINT_DECREASE_VALUE = 2

POINT_PER_HP = 5
TOTAL_TIME = 180
FRAME_TIME = 10
TOTAL_LIFE = 5

## Enable
ENABLE_CHEAT = False
ENABLE_AUTO = False
ENABLE_SFX = True
ENABLE_MUSIC = False


## Path
MAP_FOLDER = '/Users/lap14008/Programming/Game Programming/pygame/res/maps/'
DEFAULT_MAP = '/Users/lap14008/Programming/Game Programming/pygame/res/map.json'

## Credit
VERSION = "1.0"
AUTHOR = "Son Bui"